### PR TITLE
Discord link revert

### PR DESCRIPTION
**Pull request by mrbasado**

### CODE REVIEW

**Comment by GalloDaSballo** [comment]
Not convinced it will provide any guarantee as even if we own the link the risk of hijacking is non-zero

On the other hand risk of simulating a pseudo-random string is lower

**Comment by GalloDaSballo** [comment]
It may be possible to reproduce the string via boost as well, not sure

**Comment by mrbasado** [comment]
I agree this is more a product desire, I think there is value in making the discord.badger.com 301 redirect nginx server to point to whatever we want (this gives us more control if we use the link in permeant tweets and if discord increase number of boosts to keep this feature). In regards to the boost link Will now owns the minimal amount of boosts needed for the feature.

**Comment by GalloDaSballo** [comment]
Don't think it's worth pushing the fix out with any urgency

I'd prefer listening to other people's thoughts

**Comment by GalloDaSballo** [comment]
Correction the link is expired

**Pull request merged**
